[project]
name = "valuation-stocks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "flask>=3.0.3",
    "pandas>=2.0.3",
    "yfinance>=0.2.61",
]
